In [43]:
#run this program on python shell
import tensorflow as tf
# Creates a graph.
x = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[1, 6], name='a')
y = tf.constant([1.0, 2.0, 9.0, 4.0, 7.0, 6.0], shape=[1, 6], name='b')

with tf.name_scope("mean_scope"):
    mean_x=tf.reduce_mean(x)
    mean_y=tf.reduce_mean(y)
   ## tf.multiply()
    
sess=tf.Session()
print(sess.run(mean_x))


3.5


In [44]:
##Calculate variance for x variance(x)=sum((x-mean(x))^2)

with tf.name_scope("VARIANCE_scope"):
    a1=tf.subtract(x,mean_x)
    sess=tf.Session()
    print(sess.run(a1))

    a2=tf.square(a1)
    var_x=tf.reduce_sum(a2)

    sess=tf.Session()
    print(sess.run(var_x))


[[-2.5 -1.5 -0.5  0.5  1.5  2.5]]
17.5


In [45]:

##Calculate covariance of x & y covariance = sum((x(i) - mean(x)) * (y(i) - mean(y)))
with tf.name_scope("covariance_scope"):
    m=tf.subtract(x,mean_x)
    sess=tf.Session()
    print(sess.run(m))

    n=tf.subtract(y,mean_y)
    sess=tf.Session()
    print(sess.run(n))

    o=tf.multiply(m,n)
    sess=tf.Session()
    print(sess.run(o))

    cov=tf.reduce_sum(o)

    sess=tf.Session()
    print(sess.run(cov))


[[-2.5 -1.5 -0.5  0.5  1.5  2.5]]
[[-3.83333349 -2.83333349  4.16666651 -0.83333349  2.16666651  1.16666651]]
[[ 9.58333397  4.25       -2.08333325 -0.41666675  3.24999976  2.91666627]]
17.5


In [46]:
##Calculate value of c c = covariance(x,y)/variance(x)
with tf.name_scope("value_c_scope"):
    value_c=tf.divide(cov,var_x)
    sess=tf.Session()
    print(sess.run(value_c))

1.0


In [49]:
##Calculate value of m m = mean(y) -c* mean(x)
with tf.name_scope("value_of_m_scope"):
    r=tf.multiply(value_c,mean_x)
    value_m=tf.subtract(mean_y,r)

    sess=tf.Session()
    print(sess.run(value_m))

1.33333


In [50]:
 writer = tf.summary.FileWriter("/tmp/tboard/output3", sess.graph)